site_name: Superflows

theme:
  name: material
  logo: assets/logo_invert.png
  favicon: assets/logo_black.png
  features:
    - content.code.copy
    - content.code.select
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

copyright: Copyright &copy; 2024 <a href="flagggrc.tech">FlaggGRC Techlabs LLP</a>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences